[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.0"

[tool.ruff]
line-length = 120
target-version = "py311"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B"]
ignore = ["E501"]
